set_property BITSTREAM.GENERAL.COMPRESS true [current_design]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T3 PULLDOWN true} [get_ports A]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN U3 PULLDOWN true} [get_ports B]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN T4 PULLDOWN true} [get_ports C]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V3 PULLDOWN true} [get_ports G1]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN V4 PULLDOWN true} [get_ports G2A]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN W4 PULLDOWN true} [get_ports G2B]

set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN R1} [get_ports Y[0]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN P2} [get_ports Y[1]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN P1} [get_ports Y[2]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN N2} [get_ports Y[3]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN M1} [get_ports Y[4]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN M2} [get_ports Y[5]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN L1} [get_ports Y[6]]
set_property -dict {IOSTANDARD LVCMOS18 PACKAGE_PIN J2} [get_ports Y[7]]
